config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"

  root "homes#index"

  devise_for :users,
             path: "",
             path_names: {
               sign_in: "login",
               sign_up: "registration",
               sign_out: "logout"
             }

  get "message", to: "messages#index"
  post "message", to: "messages#create"
  get "message/:id", to: "messages#show", as: "show_messages"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  scope :get_messages, (lambda do |sender_id, receiver_id|
    where("sender_id = #{sender_id} AND receiver_id = #{receiver_id}")
      .or(where("sender_id = #{receiver_id} AND receiver_id = #{sender_id}"))
  end)

  def send_message
    ActionCable.server.broadcast "room_channel:#{receiver_id}",
                                 message: message,
                                 sender_id: sender_id
    ActionCable.server.broadcast "room_channel:#{sender_id}",
                                 message: message,
                                 sender_id: sender_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sent_messages,
           class_name: Message.name,
           foreign_key: :sender_id,
           dependent: :destroy
  has_many :received_messages,
           class_name: Message.name,
           foreign_key: :receiver_id,
           dependent: :destroy

  scope :except_id, ->(id){where.not id: id}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    render "layouts/index"
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :load_users
  before_action :load_user, only: :show

  def index; end

  def show
    @msg = Message.new
    @messages = Message.get_messages current_user.id, params[:id]
  end

  def create
    message = Message.new message_params
    return unless message.save

    message.send_message
  end

  private

  def message_params
    params.require(:message).permit :message, :sender_id, :receiver_id
  end

  def load_users
    @users = @users = User.except_id current_user.id
  end

  def load_user
    @partner_user = User.find_by id: params[:id]
    return if @partner_user

    redirect_to message_path
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  protected

  def update_resource resource, params
    return super if params["password"]&.present?

    resource.update_without_password(params.except("current_password"))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav pull-right">
      <% if user_signed_in? %>
        <li><%= link_to current_user.email, "#", class: "nav-link" %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
      <% else %>
        <li><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
        <li><%= link_to "Registration", new_user_registration_path, class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="h-100">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/index.html.erb
<h1 class="text-center">Chat online</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <p>Chat online</p>
  </div>
</div>

app/views/messages/_form.html.erb
<div class="card-footer">
  <%= form_for @msg, url: message_path, method: :post, remote: true do |f| %>
    <div class="input-group">
      <%= f.hidden_field :sender_id, value: current_user.id %>
      <%= f.hidden_field :receiver_id, value: @partner_user.id %>
      <%= f.text_field :message, class: "form-control type_msg" %>
      <div class="input-group-append">
        <span class="input-group-text send_btn"><i class="fas fa-location-arrow"></i></span>
      </div>
    </div>
  <% end %>
</div>
<%= javascript_pack_tag "messages" %>

app/views/messages/_message.html.erb
<% if !current_user.id.eql? msg.sender_id %>
  <div class="d-flex justify-content-start mb-4">
    <div class="img_cont_msg">
      <img src="https://static.turbosquid.com/Preview/001292/481/WV/_D.jpg" class="rounded-circle user_img_msg">
    </div>
    <div class="msg_cotainer">
      <%= msg.message %>
    </div>
  </div>
<% else %>
  <div class="d-flex justify-content-end mb-4">
    <div class="msg_cotainer_send">
      <%= msg.message %>
    </div>
    <div class="img_cont_msg">
      <img src="https://static.turbosquid.com/Preview/001292/481/WV/_D.jpg" class="rounded-circle user_img_msg">
    </div>
  </div>
<% end %>

app/views/messages/_user.html.erb
<li class="<%= "active" if user.id.eql? request.url.slice(30).to_i %>">
  <%= link_to show_messages_path user.id do %>
    <div class="d-flex bd-highlight">
      <div class="img_cont">
        <%= image_tag "https://static.turbosquid.com/Preview/001292/481/WV/_D.jpg", class: "rounded-circle user_img" %>
        <span class="online_icon"></span>
      </div>
      <div class="user_info">
        <span><%= user.email %></span>
        <p>Online</p>
      </div>
    </div>
  <% end %>
</li>

app/views/messages/_users.html.erb
<div class="col-md-4 col-xl-3 chat">
  <div class="card mb-sm-3 mb-md-0 contacts_card">
    <div class="card-body contacts_body">
      <ui class="contacts">
        <%= render partial: "user", collection: @users, as: :user %>
      </ui>
    </div>
  </div>
</div>

app/views/messages/index.html.erb
<%= render "users" %>

app/views/messages/show.html.erb
<%= render "users" %>
<div class="col-md-8 col-xl-6 chat">
  <div class="card">
    <div class="card-header msg_head">
      <div class="d-flex bd-highlight">
        <div class="img_cont">
          <img src="https://static.turbosquid.com/Preview/001292/481/WV/_D.jpg" class="rounded-circle user_img">
          <span class="online_icon"></span>
        </div>
        <div class="user_info">
          <span><%= @partner_user.email %></span>
        </div>
      </div>
    </div>
    <div class="card-body msg_card_body">
      <%= render partial: "message", collection: @messages, as: :msg %>
    </div>
    <%= render "form" %>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br/>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br/>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br/>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br/>
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br/>
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %>
    <br/>
  <% end %>
<% end %>